language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - CHECK="normal"

matrix:
  include:
    ## distcheck
    - os: linux
      compiler: gcc
      env: CHECK="distcheck"

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-get -qq update && sudo apt-get install -qq
        texinfo
        texlive
        liblzma-dev
      ;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update >/dev/null; brew install
        homebrew/science/hdf5
      ;
    fi

before_script:
  - autoreconf -vfi
  - MAKE="make -j2"

script:
  - ./configure CPPFLAGS="-DDEBUG_FLAG" --with-matlab || { cat config.log; false; }
  - if [ "$CHECK" = "normal" ]; then
      $MAKE clean && $MAKE check;
    fi
  - if [ "$CHECK" = "distcheck" ]; then
      $MAKE all && $MAKE distcheck;
    fi

after_script:
  # find test log from check as well as from distcheck
  - log=$(find -name test-suite.log) && test -f "$log" && cat "$log" || true

## whitelist
branches:
  only:
    - master
    - next
    - /^travis.*/
    - /^tmp.*/
